### ISSUE TITLE
Actionview Test failing issue (DateHelperSelectTagsI18nTests#test_select_month_with_frozen_month_names)

### ISSUE THREAD

**Issue by xmas7** [RubyOnWorld/allure-ruby#4]
**Actual behavior**
Test file: test/template/date_helper_i18n_test.rb
Running 13 tests in a single process (parallelization threshold is 50)
Run options: --seed 35591

# Running:

......E

Error:
DateHelperSelectTagsI18nTests#test_select_month_with_frozen_month_names:
ArgumentError: mocked method :call expects 2 arguments, got [:"date.month_names"]
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:907:in `translated_month_names'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:890:in `month_names'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:962:in `month_name'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:830:in `block in select_month'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:827:in `upto'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:827:in `select_month'
    /usr/share/gems/gems/actionview-7.0.4/lib/action_view/helpers/date_helper.rb:639:in `select_month'
    test/template/date_helper_i18n_test.rb:121:in `block in test_select_month_with_frozen_month_names'
    /usr/share/gems/gems/activesupport-7.0.4/lib/active_support/testing/method_call_assertions.rb:24:in `assert_called_with'
    test/template/date_helper_i18n_test.rb:120:in `test_select_month_with_frozen_month_names'

rails test test/template/date_helper_i18n_test.rb:117

**System configuration**
Rails version:
7.0.4

**Comment by mazilin1225** [comment]
This failure can be addressed by running tests using bundler.

```
bundle install
bundle exec ruby -Itest -- 'test/template/date_helper_i18n_test.rb'
```
